# Generated by Django 2.2.1 on 2019-06-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_contrato', models.IntegerField(db_column='periodo_contrato')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cliente')),
                ('id_imovel', models.ForeignKey(db_column='id_imovel', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Imovel')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
