# Generated by Django 2.2.1 on 2019-06-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='id_cliente',
        ),
    ]
