# Generated by Django 2.2.1 on 2019-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190531_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('sobrenome', models.CharField(blank=True, max_length=30)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('mensagem', models.TextField(blank=True)),
            ],
        ),
    ]
