# Generated by Django 2.2.1 on 2019-06-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_imovel_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='qtd_comodo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
