# Generated by Django 2.2.1 on 2019-06-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190604_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo_servico',
            field=models.CharField(choices=[('VE', 'Venda'), ('AL', 'Alugel'), ('VA', 'Venda e Aluguel')], default='VA', max_length=2),
        ),
    ]
