# Generated by Django 2.2.1 on 2019-06-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
