# Generated by Django 2.2.1 on 2019-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190603_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
