# Generated by Django 2.2.1 on 2019-06-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('tipo_servico', models.CharField(choices=[('VE', 'Venda'), ('AL', 'Alugel'), ('VA', 'Venda e Aluguel')], default='VA', max_length=2)),
                ('finalidade', models.CharField(choices=[('RE', 'Residencial'), ('CO', 'Comercial')], default='RE', max_length=2)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('metro', models.CharField(max_length=50)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qtd_comodo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
