# Generated by Django 2.2.1 on 2019-06-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190601_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='uf',
            field=models.CharField(max_length=10),
        ),
    ]
