# Generated by Django 2.2.1 on 2019-06-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anuncie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncie',
            name='bairro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anuncie',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='anuncie',
            name='cidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anuncie',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anuncie',
            name='finalidade',
            field=models.CharField(blank=True, choices=[('RE', 'Residencial'), ('CO', 'Comercial')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='anuncie',
            name='metro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anuncie',
            name='tipo_servico',
            field=models.CharField(blank=True, choices=[('VE', 'Venda'), ('AL', 'Alugel'), ('VA', 'Venda e Aluguel')], default='VA', max_length=2),
        ),
    ]
